name: Release the next version

on:
  workflow_dispatch:

jobs:
  release:
    runs-on: ubuntu-latest
    container:
      image: larsnieuwenhuizen/ci-helpers:latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          path: '/app/code'

      - name: Define version
        run: |
          cd /app;
          ls -al;
          ls -al /app/code;
          bin/console version:define -vvv
