name: Release the next version

on:
  workflow_dispatch:

jobs:
  release:
    runs-on: ubuntu-latest
    container:
      image: larsnieuwenhuizen/ci-helpers:latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Define new version
        id: vars
        run: |
          cp -r . /app/code;
          cp -r .git /app/code;
          cd /app/code;
          ls -al;
          cd /app;
          ls -al;
          git --git-dir=/app/code/.git tag;
          version=$(bin/console version:define);
          echo "version=$version" >> $GITHUB_OUTPUT;

      - name: Release new version
        run: |
          cp -r . /app/code;
          cp -r .git /app/code;
          cd /app/code;
          ls -al;
          cd /app;
          ls -al;
          git --git-dir=/app/code/.git tag;
          bin/console version:define -vvv;
          bin/console version:release;

      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # This token is provided by Actions, you do not need to create your own token
        with:
          tag_name: ${{ steps.vars.outputs.version }}
          release_name: Release ${{ steps.vars.outputs.version }}
          draft: false
          prerelease: false
