name: Release the next version

on:
  workflow_dispatch:

jobs:
  release:
    runs-on: ubuntu-latest
    container:
      image: larsnieuwenhuizen/ci-helpers:latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Define version
        run: |
          cp -r . /app/code;
          cp -r .git /app/code;
          cd /app/code;
          ls -al;
          cd /app;
          ls -al;
          git --git-dir=/app/code/.git tag
